/**
 * Apple Health Permissions
 * https://github.com/terrillo/rn-apple-healthkit#permissions
 * @type {Object}
 */
export const Permissions = {
  ActiveEnergyBurned: "ActiveEnergyBurned",
  AppleExerciseTime: "AppleExerciseTime",
  BasalEnergyBurned: "BasalEnergyBurned",
  BiologicalSex: "BiologicalSex",
  BloodGlucose: "BloodGlucose",
  BloodPressureDiastolic: "BloodPressureDiastolic",
  BloodPressureSystolic: "BloodPressureSystolic",
  BodyFatPercentage: "BodyFatPercentage",
  BodyMass: "BodyMass",
  BodyMassIndex: "BodyMassIndex",
  BodyTemperature: "BodyTemperature",
  DateOfBirth: "DateOfBirth",
  Biotin: "Biotin",
  Caffeine: "Caffeine",
  Calcium: "Calcium",
  Carbohydrates: "Carbohydrates",
  Chloride: "Chloride",
  Cholesterol: "Cholesterol",
  Copper: "Copper",
  EnergyConsumed: "EnergyConsumed",
  FatMonounsaturated: "FatMonounsaturated",
  FatPolyunsaturated: "FatPolyunsaturated",
  FatSaturated: "FatSaturated",
  FatTotal: "FatTotal",
  Fiber: "Fiber",
  Folate: "Folate",
  Iodine: "Iodine",
  Iron: "Iron",
  Magnesium: "Magnesium",
  Manganese: "Manganese",
  Molybdenum: "Molybdenum",
  Niacin: "Niacin",
  PantothenicAcid: "PantothenicAcid",
  Phosphorus: "Phosphorus",
  Potassium: "Potassium",
  Protein: "Protein",
  Riboflavin: "Riboflavin",
  Selenium: "Selenium",
  Sodium: "Sodium",
  Sugar: "Sugar",
  Thiamin: "Thiamin",
  VitaminA: "VitaminA",
  VitaminB12: "VitaminB12",
  VitaminB6: "VitaminB6",
  VitaminC: "VitaminC",
  VitaminD: "VitaminD",
  VitaminE: "VitaminE",
  VitaminK: "VitaminK",
  Zinc: "Zinc",
  Water: "Water",
  DistanceCycling: "DistanceCycling",
  DistanceWalkingRunning: "DistanceWalkingRunning",
  FlightsClimbed: "FlightsClimbed",
  HeartRate: "HeartRate",
  Height: "Height",
  LeanBodyMass: "LeanBodyMass",
  MindfulSession: "MindfulSession",
  NikeFuel: "NikeFuel",
  RespiratoryRate: "RespiratoryRate",
  SleepAnalysis: "SleepAnalysis",
  StepCount: "StepCount",
  Steps: "Steps",
  OxygenSaturation:"OxygenSaturation",
  forcedVitalCapacity:"ForcedVitalCapacity",
  forcedExpiratoryVolume1:"ForcedExpiratoryVolume1",
  peakExpiratoryFlowRate:"PeakExpiratoryFlowRate",
  Weight: "Weight",
  LowHeartRateEvent: "LowHeartRateEvent",
  allergyRecord: "allergyRecord",
  conditionRecord: "conditionRecord",
  immunizationRecord: "immunizationRecord",
  labResultRecord: "labResultRecord",
  medicationRecord: "medicationRecord",
  procedureRecord: "procedureRecord",
  vitalSignRecord: "vitalSignRecord",
  peripheralPerfusionIndex: "peripheralPerfusionIndex",
  electrodermalActivity: "electrodermalActivity",
  inhalerUsage: "inhalerUsage",
  insulinDelivery: "insulinDelivery",
  numberOfTimesFallen: "numberOfTimesFallen",
  walkingHeartRateAverage: "walkingHeartRateAverage",
  restingHeartRate: "restingHeartRate",
  fitzpatrickSkinType: "fitzpatrickSkinType",
  heartRateVariabilitySDNN:"heartRateVariabilitySDNN",
  VO2Max:"VO2Max",

}
